"use client"

import { Button } from "@/components/ui/button"
import type { BookType } from "@/components/book-type-selector"
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Download, Calculator } from "lucide-react"
import { useState } from "react"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { useToast } from "@/components/ui/use-toast"

type ResourcesTemplatesProps = {
  bookType: BookType
  onComplete: () => void
  onBack: () => void
}

export function ResourcesTemplates({ bookType, onComplete, onBack }: ResourcesTemplatesProps) {
  const [trimWidth, setTrimWidth] = useState("8.5")
  const [trimHeight, setTrimHeight] = useState("11")
  const [pageCount, setPageCount] = useState("40")
  const { toast } = useToast()

  const handleDownload = (templateName: string) => {
    toast({
      title: "Template downloaded",
      description: `${templateName} has been downloaded.`,
    })
  }

  const calculateCoverSize = () => {
    // Simple calculation for KDP cover size
    // For a real app, this would be more precise
    const width = Number.parseFloat(trimWidth)
    const height = Number.parseFloat(trimHeight)
    const pages = Number.parseInt(pageCount)

    // Spine width is roughly 0.002252 inches per page for white paper
    const spineWidth = (pages * 0.002252).toFixed(2)

    // KDP requires 0.125" bleed on all sides
    const coverWidth = (width + 0.25 + Number.parseFloat(spineWidth)).toFixed(2)
    const coverHeight = (height + 0.25).toFixed(2)

    toast({
      title: "Cover Size Calculated",
      description: `Full cover dimensions: ${coverWidth}" × ${coverHeight}" with a ${spineWidth}" spine.`,
    })
  }

  const handleComplete = () => {
    // Create content with project details
    const content = `
🕹️ KDP Project by Wade

📘 Book Type: ${bookType}
🎯 Niche: Mindful Dinosaurs

🧠 Prompts:
1. Write 30 positive affirmations for children featuring dinosaurs.
2. Create a mindfulness introduction for ages 4–8.
3. Design 10 dinosaur-themed activities.

🔑 Keywords:
- dinosaur mindfulness
- kids calm coloring
- emotional regulation book

📐 Trim Size: ${trimWidth}" x ${trimHeight}"
Page Count: ${pageCount}
Cover Size with bleed: ${(Number.parseFloat(trimWidth) + 0.25 + Number.parseInt(pageCount) * 0.002252).toFixed(2)}" x ${(Number.parseFloat(trimHeight) + 0.25).toFixed(2)}"

📎 Resources:
- Canva Template: [coming soon]
- KDP Guide: [coming soon]

Generated by Wade — Your Retro Publishing Sidekick.
https://v0-kdp-helper-bot-j2.vercel.app
`

    // Create and download a text file
    const blob = new Blob([content], { type: "text/plain" })
    const link = document.createElement("a")
    link.href = URL.createObjectURL(blob)
    link.download = "Wade_KDP_Project.txt"
    link.click()

    // Clean up the URL object
    setTimeout(() => URL.revokeObjectURL(link.href), 100)

    // Show success toast
    toast({
      title: "Project exported successfully!",
      description: "Your KDP project details have been downloaded.",
    })

    // Call the original onComplete function
    onComplete()
  }

  return (
    <div>
      <Tabs defaultValue="templates">
        <TabsList className="grid w-full grid-cols-3 mb-6 bg-slate-700">
          <TabsTrigger
            value="templates"
            className="data-[state=active]:bg-purple-500/20 data-[state=active]:text-purple-300"
          >
            Templates
          </TabsTrigger>
          <TabsTrigger value="sizing" className="data-[state=active]:bg-blue-500/20 data-[state=active]:text-blue-300">
            KDP Sizing Guide
          </TabsTrigger>
          <TabsTrigger
            value="calculator"
            className="data-[state=active]:bg-purple-500/20 data-[state=active]:text-purple-300"
          >
            Cover Calculator
          </TabsTrigger>
        </TabsList>

        <TabsContent value="templates" className="mt-0">
          <h3 className="text-lg font-medium mb-4">Canva Templates for {bookType}</h3>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <TemplateCard
              title="8.5 × 11 Template"
              description="US Letter size template for your book interior"
              onDownload={() => handleDownload("8.5 × 11 Template")}
            />
            <TemplateCard
              title="6 × 9 Template"
              description="Standard book size template for your book interior"
              onDownload={() => handleDownload("6 × 9 Template")}
            />
            <TemplateCard
              title="Cover Template"
              description="Full cover template with spine and bleed areas"
              onDownload={() => handleDownload("Cover Template")}
            />
            <TemplateCard
              title="Interior Elements"
              description="Page numbers, headers, and decorative elements"
              onDownload={() => handleDownload("Interior Elements")}
            />
          </div>
        </TabsContent>

        <TabsContent value="sizing" className="mt-0">
          <h3 className="text-lg font-medium mb-4">KDP Sizing & Margin Guidelines</h3>

          <Card className="bg-slate-700 border-gray-600 text-white mb-4">
            <CardHeader>
              <CardTitle className="text-lg">Trim Sizes</CardTitle>
              <CardDescription className="text-gray-300">Standard sizes for your {bookType}</CardDescription>
            </CardHeader>
            <CardContent>
              <ul className="space-y-2 text-sm text-gray-300">
                <li className="flex justify-between">
                  <span>US Letter</span>
                  <span className="font-mono">8.5" × 11"</span>
                </li>
                <li className="flex justify-between">
                  <span>Standard Book</span>
                  <span className="font-mono">6" × 9"</span>
                </li>
                <li className="flex justify-between">
                  <span>Square</span>
                  <span className="font-mono">8.5" × 8.5"</span>
                </li>
                <li className="flex justify-between">
                  <span>Children's Book</span>
                  <span className="font-mono">8" × 10"</span>
                </li>
              </ul>
            </CardContent>
          </Card>

          <Card className="bg-slate-700 border-gray-600 text-white">
            <CardHeader>
              <CardTitle className="text-lg">Margins & Bleed</CardTitle>
              <CardDescription className="text-gray-300">Required margins for KDP publishing</CardDescription>
            </CardHeader>
            <CardContent>
              <ul className="space-y-2 text-sm text-gray-300">
                <li className="flex justify-between">
                  <span>Interior Margins (min)</span>
                  <span className="font-mono">0.25" inside, 0.375" outside</span>
                </li>
                <li className="flex justify-between">
                  <span>Gutter (for binding)</span>
                  <span className="font-mono">0.125" + (0.02" × page count/100)</span>
                </li>
                <li className="flex justify-between">
                  <span>Bleed (if needed)</span>
                  <span className="font-mono">0.125" on all sides</span>
                </li>
                <li className="flex justify-between">
                  <span>Safe Zone</span>
                  <span className="font-mono">0.25" from trim edge</span>
                </li>
              </ul>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="calculator" className="mt-0">
          <h3 className="text-lg font-medium mb-4">Cover Size Calculator</h3>

          <Card className="bg-slate-700 border-gray-600 text-white">
            <CardContent className="p-6">
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
                <div className="space-y-2">
                  <Label htmlFor="trim-width" className="text-gray-300">
                    Trim Width (inches)
                  </Label>
                  <Input
                    id="trim-width"
                    type="number"
                    step="0.1"
                    value={trimWidth}
                    onChange={(e) => setTrimWidth(e.target.value)}
                    className="bg-slate-600 border-gray-500 text-white"
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="trim-height" className="text-gray-300">
                    Trim Height (inches)
                  </Label>
                  <Input
                    id="trim-height"
                    type="number"
                    step="0.1"
                    value={trimHeight}
                    onChange={(e) => setTrimHeight(e.target.value)}
                    className="bg-slate-600 border-gray-500 text-white"
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="page-count" className="text-gray-300">
                    Page Count
                  </Label>
                  <Input
                    id="page-count"
                    type="number"
                    value={pageCount}
                    onChange={(e) => setPageCount(e.target.value)}
                    className="bg-slate-600 border-gray-500 text-white"
                  />
                </div>
              </div>

              <Button
                className="w-full bg-gradient-to-r from-purple-600 to-blue-600 hover:from-purple-700 hover:to-blue-700"
                onClick={calculateCoverSize}
              >
                <Calculator size={16} className="mr-2" />
                Calculate Cover Size
              </Button>

              <div className="mt-4 text-sm text-gray-400">
                <p>
                  This calculator provides the full cover dimensions including spine width and bleed area required by
                  KDP.
                </p>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>

      <div className="flex justify-between mt-8">
        <Button variant="outline" onClick={onBack}>
          Back
        </Button>
        <Button
          className="bg-gradient-to-r from-purple-600 to-blue-600 hover:from-purple-700 hover:to-blue-700"
          onClick={handleComplete}
        >
          Complete Setup
        </Button>
      </div>
    </div>
  )
}

function TemplateCard({
  title,
  description,
  onDownload,
}: { title: string; description: string; onDownload: () => void }) {
  return (
    <Card className="bg-slate-700 border-gray-600 text-white hover:border-purple-500/50 transition-all duration-300">
      <CardHeader className="pb-2">
        <CardTitle className="text-lg">{title}</CardTitle>
        <CardDescription className="text-gray-400">{description}</CardDescription>
      </CardHeader>
      <CardFooter className="pt-2">
        <Button
          variant="outline"
          className="w-full border-purple-500/30 text-purple-400 hover:bg-purple-500/10"
          onClick={onDownload}
        >
          <Download size={16} className="mr-2" />
          Download Template
        </Button>
      </CardFooter>
    </Card>
  )
}
